name: Python CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: install packages
        run: make python_install
      - name: lint
        run: make python_lint
      - name: test
        run: make python_test
      - name: format
        run: make python_format
