name: Rust CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Check
      run: cargo check

    - name: Format
      run: cargo fmt

    - name: Test
      run: cargo test

    - name: Release
      run: cargo build --release

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Su Zhang Individual Project 2
        path: target/release/su_zhang_sqlite
